version: "3.8"

services:
  backrest:
    image: garethgeorge/backrest:latest
    container_name: backrest
    hostname: backrest
    restart: unless-stopped
    ports:
      - "9898:9898"
    volumes:
      # Backrest internal data and configuration
      - /mnt/ssd/configs/backrest/data:/data
      - /mnt/ssd/configs/backrest/config:/config
      - /mnt/ssd/configs/backrest/cache:/cache
      - /mnt/ssd/configs/backrest/tmp:/tmp
      # SSH keys for SFTP (new mount)
      - /home/mariogk/.ssh:/root/.ssh:ro
      # Data to backup: all configs in /mnt/ssd/configs
      - /mnt/ssd/configs:/userdata:ro
    environment:
      - TZ=${TZ}
      - BACKREST_DATA=/data
      - BACKREST_CONFIG=/config/config.json
      - XDG_CACHE_HOME=/cache
      - TMPDIR=/tmp
      # Uncomment to allow remote access to the UI
      # - BACKREST_PORT=0.0.0.0:9898
    networks:
      - backrest_net
    cap_add:
      - SYS_NICE

networks:
  backrest_net:
    driver: bridge
