[[stack]]
name = "example-nginx"
description = "Example nginx stack managed by Komodo ResourceSync"
deploy = true
tags = ["example", "nginx"]
[stack.config]
server_id = "local-server"
file_paths = ["stacks/example-stack/docker-compose.yml"]
git_provider = "local"
repo = "local/example-stack"
