[[resource_sync]]
name = "Homelab Sync"
[resource_sync.config]
repo = "MarioGK/Homelab"
git_account = "MarioGK"
resource_path = ["komodo/", "stacks/"]
webhook_enabled = false
managed = true
delete = true
include_user_groups = true