[[resource_sync]]
name = "Homelab Sync"
[resource_sync.config]
repo = "MarioGK/Homelab"
git_account = "MarioGK"
webhook_enabled = false
managed = true
delete = true
include_variables = true
include_user_groups = true