[[deployment]]
name = "ai1"
[deployment.config]
server = "MS01"
image.type = "Build"
image.params.build = "ai-arch"
redeploy_on_build = true
command = "sleep infinity"
volumes = """
  # volume:/container/path
/mnt/ssd/ais/ai1:/mnt/
"""