[[deployment]]
name = "ai2"
[deployment.config]
server = "MS01"
image.type = "Build"
image.params.build = "ai-arch"
redeploy_on_build = true
command = "sleep infinity"
volumes = """
/mnt/ssd/ais/ai2:/mnt/
"""