services:
  traefik:
    image: traefik:latest
    container_name: traefik_local_gateway
    restart: unless-stopped
    command:
      - --providers.file.directory=/etc/traefik/dynamic
      - --providers.file.watch=true
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
      - --api.insecure=true
      - --log.level=INFO
    ports:
      - "80:80"
      - "443:443"
      - "8088:8080" # Traefik dashboard (optional)
    volumes:
      - ./traefik:/etc/traefik:ro