services:
  headscale-ui:
    image: ghcr.io/gurucomputing/headscale-ui:latest
    container_name: headscale-ui
    restart: unless-stopped
    ports:
      - "6081:8080"
      #- "8444:8443"
    environment:
      - TZ=${TZ}
      - HTTP_PORT=8080
      - HTTPS_PORT=8443
    depends_on:
      - headscale
    networks:
      - headscale-network

  headscale:
    image: ghcr.io/juanfont/headscale:latest
    container_name: headscale
    restart: unless-stopped
    ports:
      - "6080:8080"
      - "50443:50443"
      - "3478:3478/udp"
    volumes:
      - /mnt/ssd/configs/headscale:/var/lib/headscale
      - ./config.yaml:/etc/headscale/config.yaml:ro
    environment:
      - TZ=${TZ}
    networks:
      - headscale-network
    command: serve

networks:
  headscale-network:
    driver: bridge
