[[procedure]]
name = "Sync"
config.webhook_secret = "KomodoHomelab"

[[procedure.config.stage]]
name = "Stage 1"
enabled = true
executions = [
  { execution.type = "CloneRepo", execution.params.repo = "MarioGK/Homelab", enabled = true }
]

[[procedure.config.stage]]
name = "Stage 2"
enabled = true
executions = [
  { execution.type = "CloneRepo", execution.params.repo = "MarioGK/Homelab", enabled = true }
]

[[procedure.config.stage]]
name = "Stage 3"
enabled = true
executions = [
  { execution.type = "BatchDeployStackIfChanged", execution.params.pattern = "*", enabled = true }
]