[[stack]]
name = "ai"
[stack.config]
deploy = true
server = "MS01"
linked_repo = "MarioGK/Homelab"
poll_for_updates = true
auto_update = true
auto_update_all_services = true
run_directory = "composes/ai/"

environment = """
## Required

## Timezone (must be America/Sao_Paulo)
TZ = "America/Sao_Paulo"
"""

[[variable]]
name = "TZ"
value = "America/Sao_Paulo"
is_secret = false

[[provision]]
name = "pre_deploy"
[provision.config]
commands = [
    # Create config dir for AI containers
    "mkdir -p /mnt/ssd/ais",
    #"chown -R 1000:1000 /mnt/ssd/ais",
    "chmod -R 777 /mnt/ssd/ais",

    #Create individual dirs for each container
    "mkdir -p /mnt/ssd/ais/ai1",
    "mkdir -p /mnt/ssd/ais/ai2",
    "mkdir -p /mnt/ssd/ais/ai3",
    "mkdir -p /mnt/ssd/ais/ai4",
    "mkdir -p /mnt/ssd/ais/ai5",
]