[[stack]]
name = "music"
[stack.config]
server = "MS01"
linked_repo = "MarioGK/Homelab"

links = ["media.mariogk.com"]
poll_for_updates = true
auto_update = true
auto_update_all_services = true
run_directory = "composes/music/"

environment = """
## Required

## Timezone (must be America/Sao_Paulo)
TZ = "America/Sao_Paulo"

## Optional: set service-specific env vars here
#PUID=1000
#PGID=1000
"""

[[variable]]
name = "TZ"
value = "America/Sao_Paulo"
is_secret = false

[[provision]]
name = "pre_deploy"
[provision.config]
commands = [
	# Create base configs dir
	"mkdir -p /mnt/ssd/configs/yMusicLite",
	"mkdir -p /mnt/ssd/configs/navidrome",
	"mkdir -p /mnt/ssd/configs/navidrome/cache",
	
	"sudo find /mnt -exec chmod 777 {} +"
]
