upstreams:
  groups:
    default:
      - 1.1.1.1
      - 1.0.0.1
      - 8.8.8.8
      - 8.8.4.4

blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - ads

caching:
  minTime: 5m
  maxTime: 60m
  prefetching: true
  exclude:
    - /.*\.lan$/
    - /.*\.local$/
    #- /.*\.host\.com\.(jp|fr)$/

client:
  timeout: 10s

web:
  port: 4000
  username: ""
  password: ""

hostsFile:
  filePath: /app/config/hosts
  hostsTTL: 1h
  refreshPeriod: 30m
  loading:
    strategy: fast

ports:
  dns: 53
  tls: 853
  http: 4000
