services:
  blocky:
    image: spx01/blocky:latest
    container_name: blocky
    restart: unless-stopped
    # Optional the instance hostname for logging purpose
    hostname: blocky
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "853:853/tcp" # DNS over TLS (DoT)
      - "853:853/udp"
      - "4000:4000" # Admin web UI (default)
    volumes:
      - /mnt/ssd/configs/komodo/repos/Homelab/composes/blocky/config.yml:/app/config.yml:ro
    environment:
      - TZ=${TZ}
