upstreams:
  init:
    strategy: fast
  groups:
    default:
      # example for tcp+udp IPv4 server (https://digitalcourage.de/)
      - 5.9.164.112
      # Cloudflare
      - 1.1.1.1
      - 1.0.0.1
      # Google
      - 8.8.8.8
      - 8.8.4.4
    laptop*:
      - 123.123.123.123
  strategy: parallel_best
  timeout: 2s

upstreamResolvers:
  default:
    - 5.9.164.112
    - 1.1.1.1
    - 1.0.0.1
    - 8.8.8.8
    - 8.8.4.4

blocking:
  denylists:
    ads:
      - https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
  clientGroupsBlock:
    default:
      - ads

caching:
  minTime: 5m
  maxTime: 60m
  prefetching: true
  exclude:
    - /.*\.lan$/
    - /.*\.local$/
    #- /.*\.host\.com\.(jp|fr)$/

client:
  timeout: 10s

web:
  port: 4000
  username: ""
  password: ""

hostsFile:
  filePath: /app/config/hosts
  hostsTTL: 1h
  refreshPeriod: 30m
  loading:
    strategy: fast

ports:
  dns: 53
  tls: 853
  http: 4000
