version: "3.8"

services:
  blocky:
    image: 0xerr0r/blocky:latest
    container_name: blocky_local
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "4000:4000" # Admin web UI (default)
    volumes:
      - ./config/config.yml:/app/config/config.yml:ro
      - ./hosts/hosts.zone:/app/config/hosts.zone:ro
    environment:
      - TZ=${TZ}
