services:
  ai1:
    image: archlinux:latest
    container_name: ai1
    volumes:
      - ai1-data:/mnt/ssd/ais/ai1
      - ./installRequirements.sh:/installRequirements.sh:ro
    network_mode: host
    environment:
      - CONTAINER_DOMAIN=ai1
    entrypoint: ["bash","/installRequirements.sh"]

  ai2:
    image: archlinux:latest
    container_name: ai2
    volumes:
      - ai2-data:/mnt/ssd/ais/ai2
      - ./installRequirements.sh:/installRequirements.sh:ro
    network_mode: host
    environment:
      - CONTAINER_DOMAIN=ai2
    entrypoint: ["bash","/installRequirements.sh"]

  ai3:
    image: archlinux:latest
    container_name: ai3
    volumes:
      - ai3-data:/mnt/ssd/ais/ai3
      - ./installRequirements.sh:/installRequirements.sh:ro
    network_mode: host
    environment:
      - CONTAINER_DOMAIN=ai3
    entrypoint: ["bash","/installRequirements.sh"]

  ai4:
    image: archlinux:latest
    container_name: ai4
    volumes:
      - ai4-data:/mnt/ssd/ais/ai4
      - ./installRequirements.sh:/installRequirements.sh:ro
    network_mode: host
    environment:
      - CONTAINER_DOMAIN=ai4
    entrypoint: ["bash","/installRequirements.sh"]

  ai5:
    image: archlinux:latest
    container_name: ai5
    volumes:
      - ai5-data:/mnt/ssd/ais/ai5
      - ./installRequirements.sh:/installRequirements.sh:ro
    network_mode: host
    environment:
      - CONTAINER_DOMAIN=ai5
    entrypoint: ["bash","/installRequirements.sh"]

volumes:
  ai1-data:
  ai2-data:
  ai3-data:
  ai4-data:
  ai5-data: